"""add courses index for get_courses ordering

Revision ID: 67ab36a96acc
Revises: 56d30807de16
Create Date: 2026-03-06 22:36:12.195537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67ab36a96acc'
down_revision: Union[str, Sequence[str], None] = '56d30807de16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_courses_published_created_at_id', 'courses', ['created_at', 'id'], unique=False, postgresql_where=sa.text('published = true'), postgresql_ops={'created_at': 'DESC', 'id': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_courses_published_created_at_id', table_name='courses', postgresql_where=sa.text('published = true'), postgresql_ops={'created_at': 'DESC', 'id': 'DESC'})
    # ### end Alembic commands ###
