"""initial schema: user, courses

Revision ID: e426acab7c6c
Revises: 
Create Date: 2026-03-07 21:46:20.414719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e426acab7c6c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_published_created_at_id'), table_name='courses', postgresql_where='(published = true)')
    op.create_index('ix_courses_published_created_at_id', 'courses', ['created_at', 'id'], unique=False, postgresql_where=sa.text('published = true'), postgresql_ops={'created_at': 'DESC', 'id': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_courses_published_created_at_id', table_name='courses', postgresql_where=sa.text('published = true'), postgresql_ops={'created_at': 'DESC', 'id': 'DESC'})
    op.create_index(op.f('ix_courses_published_created_at_id'), 'courses', [sa.literal_column('created_at DESC'), sa.literal_column('id DESC')], unique=False, postgresql_where='(published = true)')
    # ### end Alembic commands ###
